<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->name }} - {{ date('Y-m-d') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
            line-height: 1.6;
        }
        .section h2 {
            color: #d98323;
            border-bottom: 2px solid #d98323;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #d98323;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #d98323;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            color: #d98323;
            border-left: 4px solid #d98323;
            padding-left: 10px;
            margin-bottom: 15px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-item {
            display: table-cell;
            text-align: center;
            padding: 15px;
            border: 1px solid #ddd;
            background: #f8f9fa;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #d98323;
            display: block;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
            color: #495057;
        }
        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            color: white;
        }
        .badge-success { background-color: #28a745; }
        .badge-warning { background-color: #ffc107; color: #212529; }
        .badge-danger { background-color: #dc3545; }
        .badge-info { background-color: #17a2b8; }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .chart-placeholder {
            background: #f8f9fa;
            border: 2px dashed #ddd;
            padding: 40px;
            text-align: center;
            color: #666;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report->name }}</h1>
        <p>Generated on {{ date('F j, Y \a\t g:i A') }}</p>
        <p>Period: {{ date('M j, Y', strtotime($report->date_from)) }} - {{ date('M j, Y', strtotime($report->date_to)) }}</p>
    </div>

    @if($report->type === 'sales')
        @include('admin.reports.sections.sales', ['data' => $data])
    @elseif($report->type === 'inventory')
        @include('admin.reports.sections.inventory', ['data' => $data])
    @elseif($report->type === 'ml-analysis')
        @include('admin.reports.sections.ml-analysis', ['data' => $data])
    @elseif($report->type === 'customer-segments')
        @include('admin.reports.sections.customer-segments', ['data' => $data])
    @elseif($report->type === 'demand-forecast')
        @include('admin.reports.sections.demand-forecast', ['data' => $data])
    @elseif($report->type === 'comprehensive')
        @include('admin.reports.sections.comprehensive', ['data' => $data])
    @endif

    <div class="footer">
        <p>Generated by ChocolateSCM Business Intelligence System</p>
        <p>Report ID: {{ $report->id }} | Format: {{ strtoupper($report->format) }}</p>
    </div>
</body>
</html>
