<?php
namespace App\Helpers;

class LocationHelper
{
    public static function getRegionFromCity($city)
    {
        $map = [
            'Kampala' => 'Central',
            'Entebbe' => 'Central',
            'Gulu' => 'North',
            'Mbarara' => 'West',
            'Mbale' => 'East',
            'Jinja' => 'East',
            'Masaka' => 'Central',
            'Fort Portal' => 'West',
            'Hoima' => 'West',
            'Lira' => 'North',
            'Soroti' => 'East',
            'Kasese' => 'West',
            'Arua' => 'North',
            'Kisoro' => 'South West',
            'Kabale' => 'South West',
            'Rukungiri' => 'South West',
            'Bushenyi' => 'West',
            'Iganga' => 'East',
            'Tororo' => 'East',
            'Kiryandongo' => 'West',
            'Nakasongola' => 'Central',
            'Luwero' => 'Central',
            'Kiboga' => 'Central',
            'Kyenjojo' => 'West',
            'Kabarole' => 'West',
            'Buliisa' => 'West',
            'Kibale' => 'West',
            'Rakai' => 'Central',
            'Lyantonde' => 'Central',
            'Sembabule' => 'Central',
            'Namutumba' => 'East',
            'Mayuge' => 'East',
            'Kamuli' => 'East',
            'Bugiri' => 'East',
            'Kalangala' => 'Central',
            'Kaliro' => 'East',
            'Kakumiro' => 'Central',
            'Kagadi' => 'Central',
        ];
        return $map[$city] ?? null;
    }

    public static function getCountryFromCity($city)
    {
        $map = [
            'Kampala' => 'Central',
            'Entebbe' => 'Central',
            'Gulu' => 'North',
            'Mbarara' => 'West',
            'Mbale' => 'East',
            'Jinja' => 'East',
            'Masaka' => 'Central',
            'Fort Portal' => 'West',
            'Hoima' => 'West',
            'Lira' => 'North',
            'Soroti' => 'East',
            'Kasese' => 'West',
            'Arua' => 'North',
            'Kisoro' => 'South West',
            'Kabale' => 'South West',
            'Rukungiri' => 'South West',
            'Bushenyi' => 'West',
            'Iganga' => 'East',
            'Tororo' => 'East',
            'Kiryandongo' => 'West',
            'Nakasongola' => 'Central',
            'Luwero' => 'Central',
            'Kiboga' => 'Central',
            'Kyenjojo' => 'West',
            'Kabarole' => 'West',
            'Buliisa' => 'West',
            'Kibale' => 'West',
            'Rakai' => 'Central',
            'Lyantonde' => 'Central',
            'Sembabule' => 'Central',
            'Namutumba' => 'East',
            'Mayuge' => 'East',
            'Kamuli' => 'East',
            'Bugiri' => 'East',
            'Kalangala' => 'Central',
            'Kaliro' => 'East',
            'Kakumiro' => 'Central',
            'Kagadi' => 'Central',
            'Nairobi' => 'Central',
            'Mombasa' => 'Central',
            'Kigali' => 'Central',
            'Butare' => 'Central',

        ];

        $countryMap = [
            // Uganda cities
            'Kampala' => 'UG',
            'Entebbe' => 'UG',
            'Gulu' => 'UG',
            'Mbarara' => 'UG',
            'Mbale' => 'UG',
            'Jinja' => 'UG',
            'Masaka' => 'UG',
            'Fort Portal' => 'UG',
            'Hoima' => 'UG',
            'Lira' => 'UG',
            'Soroti' => 'UG',
            'Kasese' => 'UG',
            'Arua' => 'UG',
            'Kisoro' => 'UG',
            'Kabale' => 'UG',
            'Rukungiri' => 'UG',
            'Bushenyi' => 'UG',
            'Iganga' => 'UG',
            'Tororo' => 'UG',
            'Kiryandongo' => 'UG',
            'Nakasongola' => 'UG',
            'Luwero' => 'UG',
            'Kiboga' => 'UG',
            'Kyenjojo' => 'UG',
            'Kabarole' => 'UG',
            'Buliisa' => 'UG',
            'Kibale' => 'UG',
            'Rakai' => 'UG',
            'Lyantonde' => 'UG',
            'Sembabule' => 'UG',
            'Namutumba' => 'UG',
            'Mayuge' => 'UG',
            'Kamuli' => 'UG',
            'Bugiri' => 'UG',
            'Kalangala' => 'UG',
            'Kaliro' => 'UG',
            'Kakumiro' => 'UG',
            'Kagadi' => 'UG',
            'Nairobi' => 'KE',
            'Mombasa' => 'KE',
            'Kigali' => 'RW',
            'Butare' => 'RW',
        ];
        return $countryMap[$city] ?? 'UG';
    }
}